### ISSUE TITLE
为什么ONNX推理得到的框比yolo推理的框多这么多

### ISSUE THREAD

**Issue by fandy0123456** [BaofengZan/yolov7-pose-e2e-trt#10]
使用yolov7-w6-pose.onnx推理得到的shape是 _[1, 57375  57]_，没有进行nms处理
使用yolov7-w6-pose.pt推理得到的shape是 _[1, 4080，  57]_，没有进行nms处理
onnx推理的结果我能理解，_57375 = 3*(120 * 120 + 60 * 60 + 30 * 30 + 15 * 15)_
但是yolo和onnx推理后数量相差十倍，不懂yolo怎么处理的

**Comment by fandy0123456** [comment]
我使用yolov7-w6-pose.pt推理时，通过打印IKeypoint->forward()中的x值发现，4080 = 3*(32*32+16*16+8*8+4*4)
但是onnx文件是同一个pt文件导出的，为什么pt模型和onnx模型输出不一样

**Comment by fandy0123456** [comment]
我用pt推理的图片尺寸是256*256的，
用onnx推理时是960*960的，应该是这个原因吧

**Comment by DennisJcy** [comment]
框多检查下导出IOU阈值
